# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqTggIpNB5D0VseCmjZ0mX1Qx0dndD6D

Matplotlib:
useful in making plots
"""

# importing
import matplotlib.pyplot as plt

#import numpy to get data fpr out plots
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)
z = np.cos(x)

print(x)

print(y)

print(z)

"""plotting the data"""

# sine wave
plt.plot(x, y)
plt.show()

plt.plot(x, z)
plt.show()

# adding title to x-axsis and y-axsis labels
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.title('Sine Wave')
plt.show()

# plot a parabola
x = np.linspace(-10, 10, 20)
y = x**2
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Parabola')
plt.show()

plt.plot(x, y, 'r+')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Parabola')
plt.show()

plt.plot(x, y, 'g--')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Parabola')
plt.show()

plt.plot(x, y, 'rx')
plt.show()

x = np.linspace(-5, 5, 50)
plt.plot(x, np.sin(x), 'g--')
plt.plot(x, np.cos(x), 'r--')
plt.show()

# bar plot
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
languages = ['English', 'French', 'German', 'Bangla', 'Chinese']
people = [100, 85, 67, 43, 21]
ax.bar(languages, people)
plt.xlabel('Languages')
plt.ylabel('Number of People')
plt.title('Programming Languages')
plt.show()

#Pie Chart
fig1 = plt.figure()
ax1 = fig1.add_axes([0,0,1,1])
languages = ['English', 'French', 'German', 'Bangla', 'Chinese']
people = [100, 85, 67, 43, 21]
ax1.pie(people, labels = languages, autopct='%1.1f')
plt.show()

#Scatter Plot
x = np.linspace(0, 10, 30)
y = np.sin(x)
z = np.cos(x)
fig2 = plt.figure()
ax2 = fig2.add_axes([0,0,1,1])
ax2.scatter(x,y,color='r')
ax2.scatter(x,z,color='b')
plt.show()

#3d scatter plot
fig3 = plt.figure()
ax = plt.axes(projection='3d')
z = 20 * np.random.random(100)
x = np.sin(z)
y = np.cos(z)
ax.scatter(x, y, z, c=z, cmap='Greens')
plt.show()

